### ISSUE TITLE
This is excellent

### ISSUE THREAD

**Issue by readeral** [matt-downs/neto-api-node#6]
Great to see this library existing! Not that using fetch et al was a poor way of interacting with Neto, but great to see modern javascript from Neto staff (without Jquery!!)

I'm just in the process of creating a slightly more user-definable integration between Neto and Xero, and might look at using your library instead of wrangling my own http requests, might roll it into my other Neto related projects as well.

**Comment by matt-downs** [comment]
@readeral awesome to hear the feedback! 😀

If you do end up using this package, let me know if there are any other features that would integrate well, or if you have any issues etc. 

I’ll try and get those accounting endpoints added as soon as I can lol
